-- MySQL Script generated by MySQL Workbench
-- Thu Nov 26 13:52:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Bookish
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Bookish` ;

-- -----------------------------------------------------
-- Schema Bookish
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bookish` DEFAULT CHARACTER SET utf8 ;
USE `Bookish` ;

-- -----------------------------------------------------
-- Table `Bookish`.`Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bookish`.`Book` ;

CREATE TABLE IF NOT EXISTS `Bookish`.`Book` (
  `isbn` VARCHAR(13) NOT NULL,
  `name` MEDIUMTEXT NOT NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`isbn`),
  UNIQUE INDEX `isbn_UNIQUE` (`isbn` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bookish`.`Author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bookish`.`Author` ;

CREATE TABLE IF NOT EXISTS `Bookish`.`Author` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bookish`.`BookAuthor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bookish`.`BookAuthor` ;

CREATE TABLE IF NOT EXISTS `Bookish`.`BookAuthor` (
  `authorId` INT NOT NULL,
  `bookIsbn` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`bookIsbn`, `authorId`),
  INDEX `isbn_idx` (`bookIsbn` ASC) VISIBLE,
  CONSTRAINT `bookAuthorId`
    FOREIGN KEY (`authorId`)
    REFERENCES `Bookish`.`Author` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bookAuthorIsbn`
    FOREIGN KEY (`bookIsbn`)
    REFERENCES `Bookish`.`Book` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bookish`.`Member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bookish`.`Member` ;

CREATE TABLE IF NOT EXISTS `Bookish`.`Member` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bookish`.`Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bookish`.`Genre` ;

CREATE TABLE IF NOT EXISTS `Bookish`.`Genre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` MEDIUMTEXT NOT NULL,
  `ageGroup` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bookish`.`BookGenre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bookish`.`BookGenre` ;

CREATE TABLE IF NOT EXISTS `Bookish`.`BookGenre` (
  `genreId` INT NOT NULL,
  `bookIsbn` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`genreId`, `bookIsbn`),
  INDEX `isbn_idx` (`bookIsbn` ASC) VISIBLE,
  CONSTRAINT `bookGenreId`
    FOREIGN KEY (`genreId`)
    REFERENCES `Bookish`.`Genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bookGenreIsbn`
    FOREIGN KEY (`bookIsbn`)
    REFERENCES `Bookish`.`Book` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bookish`.`BookCopy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bookish`.`BookCopy` ;

CREATE TABLE IF NOT EXISTS `Bookish`.`BookCopy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bookIsbn` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `isbn_idx` (`bookIsbn` ASC) VISIBLE,
  CONSTRAINT `isbn`
    FOREIGN KEY (`bookIsbn`)
    REFERENCES `Bookish`.`Book` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bookish`.`Loan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bookish`.`Loan` ;

CREATE TABLE IF NOT EXISTS `Bookish`.`Loan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `memberId` INT NOT NULL,
  `copyId` INT NOT NULL,
  `loanTime` DATETIME NOT NULL,
  `dueDate` DATE NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`memberId` ASC) VISIBLE,
  INDEX `id_idx1` (`copyId` ASC) VISIBLE,
  CONSTRAINT `loanMemberId`
    FOREIGN KEY (`memberId`)
    REFERENCES `Bookish`.`Member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `LoanBookCopyId`
    FOREIGN KEY (`copyId`)
    REFERENCES `Bookish`.`BookCopy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
