-- MySQL Script generated by MySQL Workbench
-- Thu Nov 26 11:45:48 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Bookish
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Bookish
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bookish` DEFAULT CHARACTER SET utf8 ;
USE `Bookish` ;

-- -----------------------------------------------------
-- Table `Bookish`.`Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bookish`.`Author` (
  `idAuthor` INT NOT NULL AUTO_INCREMENT,
  `name` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`idAuthor`),
  UNIQUE INDEX `idAuthor_UNIQUE` (`idAuthor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bookish`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bookish`.`Book` (
  `isbn` VARCHAR(13) NOT NULL,
  `Name` MEDIUMTEXT NOT NULL,
  `Description` LONGTEXT NULL,
  PRIMARY KEY (`isbn`),
  UNIQUE INDEX `id_UNIQUE` (`isbn` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bookish`.`AuthorBook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bookish`.`AuthorBook` (
  `isbn` VARCHAR(13) NOT NULL,
  `authorId` INT NOT NULL,
  PRIMARY KEY (`isbn`, `authorId`),
  INDEX `id_idx` (`authorId` ASC) VISIBLE,
  CONSTRAINT `isbn`
    FOREIGN KEY (`isbn`)
    REFERENCES `Bookish`.`Book` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`authorId`)
    REFERENCES `Bookish`.`Author` (`idAuthor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
